version: "3.8"
services:
  shelly-em-emulator:
    build: ./shelly-em-emulator
    container_name: shelly_em_emulator
    environment:
      - HOMEWIZARD_HOST=192.168.1.50   # <- jouw HW P1 IP
      - POLL_INTERVAL=2                # seconden
      - HTTP_PORT=8080
      - DEVICE_NAME=ShellyEM-EMU
    ports:
      - "8080:8080"
    restart: unless-stopped
